# Generated by Django 2.2.5 on 2019-09-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
