# Generated by Django 2.2.5 on 2019-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0002_auto_20190914_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='attraction_list',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
