# Generated by Django 2.2.5 on 2019-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0003_pontoturistico_attraction_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comment_list',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
