# Generated by Django 2.2.5 on 2019-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('core', '0004_pontoturistico_comment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='review_list',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
