# Generated by Django 2.2.5 on 2019-09-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('core', '0005_pontoturistico_review_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='location',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
