# Generated by Django 2.2.5 on 2019-09-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
