# Generated by Django 2.2.5 on 2019-09-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190915_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='location',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
