# Generated by Django 2.2.5 on 2019-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
        ('core', '0008_auto_20190915_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='mock_test',
            field=models.ManyToManyField(to='teste.Teste'),
        ),
    ]
